### PR TITLE
Adding Portuguese baseline and Portuguese (Portugal)

### PR DESCRIPTION
**Pull request by ner00**
The baseline is added to serve other Portuguese-speaking users not immediately covered by the Brazilian or European variants, like Angola or Mozambique.

I just now noticed the Transifex project, do you want me to cancel this PR and go through Transifex? I'm fairly familiar with its, but since this seems to be the first implementation of this particular language maybe you can pull directly?

Thanks for the awesome work!

### CODE REVIEW

**Comment by prsnbrg** [comment]
Duplicate of https://github.com/wewewe718/QrAndBarcodeScanner/pull/106?

**Comment by ner00** [comment]
> Duplicate of #106?

Different branches, but otherwise yes.

**Comment by prsnbrg** [comment]
Sorry, I have overlooked this.

You can also change the target branch.
As far as I know, all changes are always integrated into develop-branch.

**Comment by ner00** [comment]
I wasn't sure, that's why I submitted both PRs, I can close the redundant one if required.

**Comment by ner00** [comment]
Closing this in favor of the PR for development branch.

**Pull request closed without merging**
